language: c++

sudo: required

services:
- docker

env: SH="docker exec -t build-image bash -c"

before_install:
- docker run -d --name build-image -u build -v $(pwd):/home/build/grapenlp-core -w /home/build/grapenlp-core grapenlp/core-build-ubuntu:16.04 tail -f /dev/null
- docker ps

install:
- mkdir bin
- sudo chown 1000:1000 bin

script:
- $SH "build/scripts/build.sh release"

notifications:
  email: true

