language: c++

sudo: required

services:
- docker

env: SH="docker exec -t build-image bash -c"

before_install:
- docker run -d --name build-image -u build -v $(pwd):/home/build/travis -w /home/build/travis grapenlp/core-build-ubuntu:16.04 tail -f /dev/null
- docker ps

install:

script:
- $SH "build/scripts/build.sh release"

notifications:
  email: true
